import * as Joi from 'joi';

export default () =>
  Joi.object({
    APP_NAME: Joi.string().default('stratyix API Server'),
    NODE_ENV: Joi.string().valid('dev', 'prod').default('dev'),
    PORT: Joi.number().default(4000),
    API_PREFIX: Joi.string().default('/api'),
    API_VERSION: Joi.string(),
    CLIENT_URL: Joi.string().default('http://localhost:3000'),
    ANALYTICS_SERVER_URL: Joi.string().default('http://localhost:3002'),
    CORS_ORIGIN: Joi.string().default('http://localhost:3000'),
    DB_HOST: Joi.string().required(),
    DB_PORT: Joi.number().default(27017),
    DB_USERNAME: Joi.string().optional(),
    DB_PASSWORD: Joi.string().optional(),
    DB_NAME: Joi.string().required(),
    REDIS_HOST: Joi.string().default('localhost'),
    REDIS_USERNAME: Joi.string().allow('').optional(),
    REDIS_PASSWORD: Joi.string().allow('').optional(),
    REDIS_PORT: Joi.number().default(6379),
    REDIS_RETRY: Joi.number().default(5),
    REDIS_DELAY: Joi.number().default(3000),
    WS_URL: Joi.string().default('ws://localhost'),
    WS_PORT: Joi.number().default(5678),
    JWT_SECRET: Joi.string().required(),
    JWT_EXPIRES_IN: Joi.string().required(),
    JWT_REFRESH_SECRET: Joi.string().required(),
    JWT_REFRESH_EXPIRES_IN: Joi.string().required(),
  });
