/**
 * Application-specific error codes
 * These provide more detailed error information than HTTP status codes
 */
export enum ErrorCode {
  // Authentication & Authorization Errors (1xxx)
  AUTH_INVALID_CREDENTIALS = 1001,
  AUTH_TOKEN_EXPIRED = 1002,
  AUTH_TOKEN_INVALID = 1003,
  AUTH_UNAUTHORIZED = 1004,
  AUTH_USER_NOT_FOUND = 1005,
  AUTH_USER_ALREADY_EXISTS = 1006,
  AUTH_WEAK_PASSWORD = 1007,
  AUTH_INVALID_EMAIL = 1008,

  // Validation Errors (2xxx)
  VALIDATION_FAILED = 2001,
  VALIDATION_MISSING_FIELD = 2002,
  VALIDATION_INVALID_FORMAT = 2003,
  VALIDATION_OUT_OF_RANGE = 2004,

  // Resource Errors (3xxx)
  RESOURCE_NOT_FOUND = 3001,
  RESOURCE_ALREADY_EXISTS = 3002,
  RESOURCE_CONFLICT = 3003,

  // Business Logic Errors (4xxx)
  BACKTEST_FAILED = 4001,
  BACKTEST_INVALID_STRATEGY = 4002,
  BACKTEST_INVALID_DATE_RANGE = 4003,
  TRADING_INSUFFICIENT_FUNDS = 4004,
  TRADING_MARKET_CLOSED = 4005,

  // Database Errors (5xxx)
  DATABASE_CONNECTION_FAILED = 5001,
  DATABASE_QUERY_FAILED = 5002,
  DATABASE_TRANSACTION_FAILED = 5003,

  // External Service Errors (6xxx)
  EXTERNAL_SERVICE_UNAVAILABLE = 6001,
  EXTERNAL_SERVICE_TIMEOUT = 6002,
  REDIS_CONNECTION_FAILED = 6003,

  // Internal Server Errors (9xxx)
  INTERNAL_SERVER_ERROR = 9001,
  UNKNOWN_ERROR = 9999,
}
